# Generated by Django 4.0.3 on 2022-05-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_order_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('api_id', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.movie'),
            preserve_default=False,
        ),
    ]
